language: java
jdk:
  - openjdk8

branches:
  only:
    - master
before_install:
  - chmod +x gradlew
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r crud-board
  - mkdir -p deploy
  - mv crud-board.zip deploy/crud-board.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: crudimage
    region: ap-northeast-2
    skip-cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - main.cpp@kakao.com