language: java
jdk:
  - openjdk8

branches:
  only:
    - master
before_install:
  - chmod +x gradlew
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - main.cpp@kakao.com