spring:
 datasource:
  jdbc-url: jdbc:h2:tcp://localhost/~/demo
  username: sa
  password:
  driver-class-name: org.h2.Driver
 #devtools:
 # restart:
 #  enabled: true
 #thymeleaf:
 # cache: false
 # prefix: file:src/main/resources/templates/

 jpa:
  hibernate:
   ddl-auto: create
  properties:
   hibernate:
    format_sql: true
  show_sql: true

logging:
 level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

cloud:
 aws:
  s3:
   bucket: crudboardimage
  region:
   static: ap-northeast-2
  stack:
   auto: false
  credentials:
   instanceProfile: true